# Generated by Django 5.1.7 on 2025-03-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiappuser',
            options={},
        ),
    ]
