# Generated by Django 5.1.7 on 2025-03-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apiappuser_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiAppuser',
            new_name='Appuser',
        ),
    ]
