# Generated by Django 5.1.7 on 2025-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_apiappuser_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'StaticQuestion',
                'verbose_name_plural': 'StaticQuestions',
                'db_table': 'static_question',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'AppUser', 'verbose_name_plural': 'AppUsers'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'managed': False, 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterModelOptions(
            name='competitionteams',
            options={'managed': False, 'verbose_name': 'Competition Team', 'verbose_name_plural': 'Competition Teams'},
        ),
        migrations.AlterModelOptions(
            name='competitionteamstudents',
            options={'managed': False, 'verbose_name': 'CompetitionTeam Student', 'verbose_name_plural': 'CompetitionTeam Students'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False, 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'managed': False, 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
