# Generated by Django 5.1.7 on 2025-03-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_staticquestion_alter_appuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticquestion',
            options={'verbose_name': 'StaticQuestion', 'verbose_name_plural': 'StaticQuestions'},
        ),
    ]
