# Generated by Django 5.1.7 on 2025-03-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_staticquestion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, db_column='question_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.staticquestion')),
                ('team', models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.competitionteams')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.appuser')),
            ],
            options={
                'verbose_name': 'StaticQuestion',
                'verbose_name_plural': 'StaticQuestions',
            },
        ),
    ]
