# Generated by Django 5.1.7 on 2025-03-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_staticanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticanswer',
            options={'verbose_name': 'StaticAnswer', 'verbose_name_plural': 'StaticAnswers'},
        ),
        migrations.AlterModelTable(
            name='staticanswer',
            table='static_answer',
        ),
    ]
