# Generated by Django 5.1.7 on 2025-03-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_staticanswer_options_alter_staticanswer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('presenter', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.competitionteams')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.appuser')),
            ],
            options={
                'verbose_name': 'StaticReport',
                'verbose_name_plural': 'StaticReports',
            },
        ),
    ]
