# Generated by Django 5.1.7 on 2025-03-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_staticreport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staticreport',
            table='static_report',
        ),
    ]
